package modelo;

public enum Permiso {
    VER_REPORTES,
    GESTIONAR_PERSONAL,
    GESTIONAR_CARTELERA,
    MODIFICAR_PRECIOS,
    OPERAR_POS,
    VALIDAR_TICKETS,
    SOLICITAR_REEMBOLSO,
    AUTORIZAR_REEMBOLSO,
    CONTROLAR_INVENTARIO,
    GESTIONAR_SALAS,
    COMPLETAR_MANTENIMIENTO,
    VER_CRONOGRAMA
}
